### ISSUE TITLE
New patch

### ISSUE THREAD

**Issue by Welinth** [jaredbwasserman/drift#55] opened 2023-07-12 00:31 UTC
Hi,

Looks like something with the new patch messed with the addon? Every time I have it enabled, I am not able to get past the loading screen. Every time I disable it, I am good to go. Wondering if others are dealing with the same or if it is just me?

Thanks

**Comment by Aur0r4** [comment] 2023-07-12 17:59
Confirmed... please update.
Sadly I cannot provide any logfiles.

**Comment by jaredbwasserman** [comment] 2023-07-13 06:19
Thanks for the heads up. Apologies for the inconvenience.

**Comment by jaredbwasserman** [comment] 2023-07-13 07:09
Unfortunately, I am not able to reproduce this. I can log into the game fine, and I am not seeing any issues when moving frames. Is it the case you're not able to enter the world at all?

**Comment by Aur0r4** [comment] 2023-07-13 18:09
I've did some more testing:
It's happening when loggin in with a character. As soon as the loading bar hits the end the game is not responding.

It is **NOT** happening when I delete the SavedVariables for Drift!

I will attach my config maybe it helps.
[Drift.zip](https://github.com/jaredbwasserman/drift/files/12042923/Drift.zip)

Thanks!

**Comment by Welinth** [comment] 2023-07-13 18:48
Confirmed the saved variables fix. Went into my account folder, savedvariables, and deleted the drift one and was able to get past the login screen

**Comment by jaredbwasserman** [comment] 2023-07-14 16:03
@Aur0r4 - I really appreciate the testing. Using your config, I am able to reproduce the issue on my side. Thanks @Welinth for the confirmation as well.
I will investigate more when I have some time.

**Comment by Aur0r4** [comment] 2023-07-15 13:57
It is 

`["miscellaneousDisabled"] = true,`

what is causing the issue.

As soon as you enable the miscellaneous box in the Drift-Options you get stuck in the loading screen.

**Comment by jaredbwasserman** [comment] 2023-07-15 18:19
Good find @Aur0r4. I isolated the issue on my side to a bad interaction between Drift and the VehicleSeatIndicator frame. The Fractures in Time update added VehicleSeatIndicator to Edit Mode (https://worldofwarcraft.blizzard.com/en-us/news/23968772/updated-july-11-dragonflight-fractures-in-time-content-update-notes-now-live#item15) which is most likely why this manifested with the new patch. I am going to disable VehicleSeatIndicator in Drift for now.

**Comment by jaredbwasserman** [comment] 2023-07-15 20:27
Fixed in Drift v2.9.9. Please reopen this issue if the problem comes back.

**Closed by jaredbwasserman** 2023-07-15 20:27 UTC
Labels: bug
