### ISSUE TITLE
Weird bug with 9.1 patch

### ISSUE THREAD

**Issue by uroshnor23** [jaredbwasserman/drift#23] opened 2021-06-29 23:08 UTC
Loading Drift in 9.1 causes  the left and right mouse buttons to not function correctly. No movement, no turning, can't even left-click on some things but can on others. Odd. I run a lot of addons, so I don't know if the problem is with 9.1 directly or perhaps an interaction with another addon.

Great addon, thanks for your efforts!

**Comment by jaredbwasserman** [comment] 2021-06-30 03:48
Hi @uroshnor23 - Sorry to hear that. I'm logging in now to see if I can reproduce this.

**Comment by jaredbwasserman** [comment] 2021-06-30 03:53
This issue is happening for me too. Thanks for reporting it. I'm working on figuring out the cause.

**Comment by uroshnor23** [comment] 2021-06-30 03:54
Thanks! Let me know if you need any more information.

**Comment by uroshnor23** [comment] 2021-06-30 03:55
Excellent! At least it wasn’t just me. :)

**Comment by jaredbwasserman** [comment] 2021-06-30 03:59
@uroshnor23 - It looks like the issue is one of the frames in the "Miscellaneous" category is causing the issue. It's possible a frame is taking up the entire screen and causing the clicks to not be registered. Can you disable "Miscellaneous" frames in the Drift options and let me know if that fixes the issue for you?

**Comment by uroshnor23** [comment] 2021-06-30 04:36
Yep! That seems to have fixed it. I don’t think I ever used anything in that category anyway. 

Thanks!

**Comment by jaredbwasserman** [comment] 2021-06-30 04:39
It turns out the problematic frame was "UIWidgetTopCenterContainerFrame" so I am removing it for the next version of the addon.

**Comment by Kalage** [comment] 2021-06-30 12:25
> Loading Drift in 9.1 causes the left and right mouse buttons to not function correctly. No movement, no turning, can't even left-click on some things but can on others. Odd. I run a lot of addons, so I don't know if the problem is with 9.1 directly or perhaps an interaction with another addon.
> 
> Great addon, thanks for your efforts!

I can confirm the same bug with this addon Drift with 9.1

I can also confirm I've had ongoing issues with drift on a few characters except my main with same bug for last month.

**Comment by jaredbwasserman** [comment] 2021-06-30 17:15
Thanks for the info @Kalage - For the ongoing issues, I'm curious which frames you have enabled. Can you let me know how you have Drift configured in the Interface Options?

**Comment by webdevdave** [comment] 2021-07-01 01:09
Just came to report this bug too... glad to see a fix and an updated release otw! :)

**Comment by jaredbwasserman** [comment] 2021-07-01 06:26
This bug should be fixed in v1.0.14.

**Closed** 2021-07-07 00:40 UTC
Labels: bug
