### ISSUE TITLE
After installing the Retail version, the mission table cannot interact.

### ISSUE THREAD

**Issue by BlueNightSky** [jaredbwasserman/drift#21] opened 2021-06-01 09:23 UTC
After installing the Retail version (v1.0.13), the covenant mission table cannot interact. :-(

Do not know why? So I can't send misson at all, very headache, I have to uninstall first.

**Comment by jaredbwasserman** [comment] 2021-06-01 17:41
Hi @BlueNightSky thanks for reporting the issue. When you tried to interact with the Covenant Mission Table, were any errors reported? Also, do you have any other AddOns that modify the Covenant Mission Table? I'm able to interact fine, so I'm not sure what could be causing the issue.

Can you try:
* `/console reloadui` to reload the UI and see if that fixes the issue
* `/drift reset` to reset Drift positions and see if that fixes the issue

**Comment by jaredbwasserman** [comment] 2021-07-01 06:25
I'm going to go ahead and close this because it is not reproducible.

**Closed by jaredbwasserman** 2021-07-01 06:25 UTC
Labels: bug
