### ISSUE TITLE
lua error 9.1.5

### ISSUE THREAD

**Issue by lenoirrichelieu** [jaredbwasserman/drift#25] opened 2021-11-10 20:53 UTC
Hi,
I keep having the following lua error

AddOns\Drift\DriftHelpers.lua:123: attempt to index local 'frame' (a nil value)
Count: 43

Call Stack:
[string "=[C]"]: ?
[string "@AddOns\Drift\DriftHelpers.lua"]:123: in function <AddOns\Drift\DriftHelpers.lua:99>
[string "@AddOns\Drift\DriftHelpers.lua"]:485: in function `ModifyFrames'
[string "@AddOns\Drift\Drift.lua"]:578: in function <AddOns\Drift\Drift.lua:570>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:509: in function `UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:686: in function `PlayerChoice_LoadUI'
[string "@FrameXML\UIParent.lua"]:2191: in function <FrameXML\UIParent.lua:1287>

I am using latest version from Curseforge in retail 9.1.5 and the only permanently moved frame is QuestTracker.

**Comment by jaredbwasserman** [comment] 2021-11-11 07:30
Hi @lenoirrichelieu - thanks for reporting this issue! I am able to reproduce it. At the moment, I do not know the cause, but it should be possible to disable the PlayerChoice frame to have the issue go away. Can you go to Interface -> AddOns -> Drift -> Options and make sure "Player Choice" is unchecked? Let me know if this does not fix the issue. When I get some time, I will look into adding a fix for this bug.

**Comment by lenoirrichelieu** [comment] 2021-11-11 17:38
Hi, 
Thank you for the fast response. I did what you recommended and the error is gone it seems. I tested with other chars where I didn't move the QuestTracker before and it was OK.

**Comment by jaredbwasserman** [comment] 2021-11-12 05:59
Glad to hear the error is gone. Thanks for the extra information about QuestTracker!

**Comment by jaredbwasserman** [comment] 2021-11-13 06:50
This should be fixed with Drift v1.0.18.

**Closed by jaredbwasserman** 2021-11-13 06:50 UTC
Labels: bug
