### ISSUE TITLE
Now it's an Issue :-)

### ISSUE THREAD

**Issue by Galthariel** [jaredbwasserman/Drift#13] opened 2020-10-16 05:01 UTC
Here I am again :-)

Took me a while to find it was Drift since I use a lot of addons (right now only the ones that are updated) but anyways. Found an issue or bug and tested several times before come here.

The issue/bug happens only in the new Barber Shop. The Accept Button (the one you need to click to make the changes) disappears when I have Drift enabled. Tried the /driftreset just in case and reloaded the UI and unfortunately not even did not work but things got even worse which I was unable to click or interact with anything on the screen. Reload again and finally everything went back to normal and I was able to click/interact with things again and the Accept Button in the Barber Shop also came back. Regardless that it's fixed now I thought you would like to know about this.

Also I would like to ask another thing in case you don't mind I use this same conversation. You know the the Toasts from Bnet? Like one a friend comes online or Quick Join? Can I also move those? 

Thanks again

**Comment by jaredbwasserman** [comment] 2020-10-16 05:56
Hi again, Galthariel! Thank you for reporting this bug! I appreciate you thoroughly testing everything.

I just released a new version of Drift on CurseForge that hopefully fixes the bug. Would you be able to download this update and confirm the Barber Shop works normally for you after the update?

The Bnet Toast frame is not currently supported by Drift, but I can definitely add it in the future! I just created a separate issue to track that here: https://github.com/jaredbwasserman/Drift/issues/14

**Comment by Galthariel** [comment] 2020-10-16 13:52
Morning or Night since I don't know where are you :-) Installed the update and the game became literally unplayed...very very slow and had to disable Drift :-(

**Comment by webdevdave** [comment] 2020-10-16 20:21
Hey @Galthariel I happened to see your question here about the Toast window. I have been using an addon, which is really great, it makes your Toast window extra cool and allows you to position it wherever you'd like... thought you might wanna check it out!

https://www.curseforge.com/wow/addons/ls-toasts

Enjoy!

**Comment by Galthariel** [comment] 2020-10-16 20:45
Thanks! I also use that one but it doesn't work with Bnet Toasts just with normal toasts

**Comment by Galthariel** [comment] 2020-10-16 22:17
Hello Jared,

After my lag spike this morning when I had to disable Drift I've enable it again by mistake (I use Better Addon List which helps me save Addons Sets and Profiles and I load a previous profile where Drift was enabled) and guess what? The horrible lag did not happened again however I cannot move or even click the Collections Window and as well all the Tabs has no names now. Reloading fixes the Tab Names issue however I can't move the Collections window still. I tried to disable all the addons that has something to do with the Collections to try find the culprit however the issue persists. 

Here is the list of addons I've disabled to test

Better Wardrobe (works with the Appearances Tab)
PetTracker (Adds a Tab called Rivals)
Rematch (Changes the Pet Journal)
Petjournal Enhanced
Toy Box Enhanced

None worked :(

**Comment by jaredbwasserman** [comment] 2020-10-17 01:41
Hi, @Galthariel - I'm glad the lag issue is no longer occurring and the Barber Shop is now working! Thanks for letting me know about the Collections window issue. I'll start to look into it.

**Comment by jaredbwasserman** [comment] 2020-10-17 01:49
Hi again, @Galthariel - I'm able to move my Collections window. Can you try a couple things to help me narrow down the issue?

1) Can you double check your Drift settings? If you go to Game Menu -> Interface -> AddOns -> Drift -> Options it will display the current Drift settings. Can you let me know if "Lock Frame Movement" is checked?
2) Is just the Collections window unable to move, or are any other windows affected?
3) Can you try disabling every AddOn except Drift? I want to be sure there is no interference. I know you mentioned you already disabled a bunch of AddOns, but I think it would help to completely isolate Drift.

Thanks!

**Comment by Galthariel** [comment] 2020-10-17 01:56
Both, Lock Frame Movement and Lock Frame Scale are unchecked. I was afraid you're going to ask me to ask me that...I use 490 Addons...and right now I have about 460 enabled since the rest is either not working or causing a lot of issues. Narrow down this is going to take a while. Will keep you posted

**Comment by Galthariel** [comment] 2020-10-17 04:03
Update:

Here is what I managed to get with BugSack. I'm not a programmer so I tried to disable PetBattleMaster because it's mentioned below but did not work so I went ahead and uninstall it completely including Saved Variables and also did not work :-(

270x Drift\DriftHelpers.lua:226: Usage: CollectionsJournal:SetPoint("point" [, region or nil] [, "relativePoint"] [, offsetX, offsetY])
[string "=[C]"]: in function `SetPoint'
[string "@Drift\DriftHelpers.lua"]:226: in function <Drift\DriftHelpers.lua:200>
[string "@Drift\DriftHelpers.lua"]:265: in function <Drift\DriftHelpers.lua:264>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2893: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2738: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2606: in function <FrameXML\UIParent.lua:2602>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3457: in function <FrameXML\UIParent.lua:3436>
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:1089: in function `SetCollectionsJournalShown'
[string "@FrameXML\UIParent.lua"]:1077: in function `ToggleCollectionsJournal'
[string "TOGGLECOLLECTIONS"]:1: in function <[string "TOGGLECOLLECTIONS"]:1>

Locals:
(*temporary) = CollectionsJournal {
 0 = <userdata>
 TitleText = CollectionsJournalTitleText {
 }
 portrait = CollectionsJournalPortrait {
 }
 SetBorder = <function> defined @SharedXML\PortraitFrame.lua:27
 layoutType = "PortraitFrameTemplate"
 DriftModifiable = true
 SetPortraitShown = <function> defined @SharedXML\PortraitFrame.lua:52
 DriftIsScaling = false
 SaveWindowPosition = <function> defined @PetBattleMaster\src\main\MovingView.lua:22
 SetPortraitAtlasRaw = <function> defined @SharedXML\PortraitFrame.lua:44
 SetPortraitToUnit = <function> defined @SharedXML\PortraitFrame.lua:36
 DriftIsMoving = false
 SetPortraitTexCoord = <function> defined @SharedXML\PortraitFrame.lua:48
 SetPortraitTextureRaw = <function> defined @SharedXML\PortraitFrame.lua:40
 SetTitleFormatted = <function> defined @SharedXML\PortraitFrame.lua:64
 NineSlice = <unnamed> {
 }
 TopTileStreaks = <unnamed> {
 }
 TitleBg = <unnamed> {
 }
 DriftSticky = true
 SetPortraitToAsset = <function> defined @SharedXML\PortraitFrame.lua:32
 SetTitleMaxLinesAndHeight = <function> defined @SharedXML\PortraitFrame.lua:68
 SetTitleColor = <function> defined @SharedXML\PortraitFrame.lua:56
 CloseButton = CollectionsJournalCloseButton {
 }
 RestoreWindowPosition = <function> defined @PetBattleMaster\src\main\MovingView.lua:11
 profile = <table> {
 }
 selectedTab = 3
 numTabs = 5
 SetTitle = <function> defined @SharedXML\PortraitFrame.lua:60
 Bg = CollectionsJournalBg {
 }
}
(*temporary) = nil
(*temporary) = "UIParent"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
_______________________________________________________________________________________________________________________________

**Comment by Galthariel** [comment] 2020-10-17 04:11
What I the error still has references to PetBattleMaster after I completely removed the Addon including all Saved Variables

RestoreWindowPosition = defined @PetBattleMaster\src\main\MovingView.lua:11

**Comment by jaredbwasserman** [comment] 2020-10-17 04:51
Thanks for all the information! I went ahead and downloaded PetBattleMaster to test. When I try to log in, I get an immediate Lua error related to PetBattleMaster, and the CollectionsJournal is unable to move. However, once I open more windows, I'm able to move around the CollectionsJournal. I'm unable to reproduce the exact issue you are seeing.

I agree it's odd the variable is still there on CollectionsJournal. One thing you can try is resetting the WoW User Interface. There are instructions here https://us.battle.net/support/en/article/7549 for how to reset the WoW User Interface.

**Comment by Galthariel** [comment] 2020-10-17 05:29
Oh man...that's something I really not going to do. I mean...reset all my UI...what if I delete teh collections Journal and then repair WoW?

**Comment by jaredbwasserman** [comment] 2020-10-17 05:35
The data in these folders gets recreated when WoW starts, so I think it should be OK. if it goes wrong, you can rename folders back to their original names and delete the newly created folders.

**Comment by Galthariel** [comment] 2020-10-17 05:48
I'll do that in the morning...Another error that happens from time to time (not always) is that as soon I login I cannot move or do anything with my mouse and if I right click in the screen my character frame starts changing the size showing the scale percentage. A simple reload fixes.

**Comment by Galthariel** [comment] 2020-10-17 17:29
Just found a folder called Blizzard_Collections under Interface/Addons which after Google it seems to be a default Blizzard folder. Move it to a Backup folder in the hope the game will recreate a new one. Log into the game and could normally access the Collections Window although the damn bug is still there and guess what? Exit and the game did not created a new Blizzard_Collections folder.

**Comment by jaredbwasserman** [comment] 2020-10-17 18:15
Hi, Galthariel, the game will not recreate the Blizzard_Collections or Blizzard_PetJournal folders as far as I know. The folders I was referring to are the ones listed in https://us.battle.net/support/en/article/7549, which are the Cache, Interface, and WTF folders.

Could you try to follow the steps in the article linked in order to reset the WoW User Interface?

Thanks!

**Comment by jaredbwasserman** [comment] 2020-10-19 07:23
I'm sorry we were unable to reach a solution. I'm going to close this issue since I'm unable to reproduce the issue.

**Closed by jaredbwasserman** 2020-10-19 07:23 UTC
Labels: bug
