### ISSUE TITLE
Broken in 9.2.7

### ISSUE THREAD

**Issue by michel-bosseaux** [jaredbwasserman/drift#32] opened 2022-08-27 10:54 UTC
Some of the windows cannot be dragged anymore since 9.2.7, like "Talking Heads".

**Comment by jaredbwasserman** [comment] 2022-08-27 16:01
Thanks for letting me know! I will take a look.

**Comment by jaredbwasserman** [comment] 2022-09-06 04:30
@michel-bosseaux - I have not noticed any issues with windows in 9.2.7. I am able to move the Talking Head frame fine. Do you have any other addons installed that may be interfering? Could you attach a screenshot of your addon settings for Drift (Interface -> Addons -> Drift)? Thanks!

**Comment by jaredbwasserman** [comment] 2022-10-24 05:25
Closing this out since I cannot reproduce.

**Closed by jaredbwasserman** 2022-10-24 05:25 UTC
Labels: bug
