### ISSUE TITLE
Color Picker Interaction Issue

### ISSUE THREAD

**Issue by dotdissent** [jaredbwasserman/Drift#19] opened 2020-12-24 22:12 UTC
Attempting to drag the options in the Color Picker windows causes Drift to kick in and start dragging the picker window around.

Before:
![image](https://user-images.githubusercontent.com/17419460/103107299-db6e7a80-460a-11eb-80f7-14ec7524d1e8.png)

After dragging the middle bar down:
![image](https://user-images.githubusercontent.com/17419460/103107318-1a9ccb80-460b-11eb-94f2-8a5eeeb8d8a7.png)

**Comment by jaredbwasserman** [comment] 2020-12-24 23:39
Thanks for the bug report! I will work on a fix when I get some time.

**Comment by jaredbwasserman** [comment] 2021-01-09 23:34
@dotdissent - Are you playing retail WoW or classic WoW? The issue is present in both versions, but it's much easier to fix in retail.

**Comment by dotdissent** [comment] 2021-01-10 01:55
Retail!

**Comment by jaredbwasserman** [comment] 2021-01-17 22:06
This bug should be fixed in the latest release of Drift (1.0.9). In order to move the Color Picker, it is now necessary to click on drag on the title bar (where it says "Color Picker"). Please re-open this ticket if you run into issues. Thanks!

**Closed by jaredbwasserman** 2021-01-17 22:06 UTC
Labels: bug
