### ISSUE TITLE
Cant move character sheet in wotlk classic

### ISSUE THREAD

**Issue by zuep** [jaredbwasserman/drift#34] opened 2022-10-05 15:13 UTC
pretty much the title. i can change the size of the character sheet but i cant move it.

moving works with all my other windows i tested so far: talents, spellbook, questlog, social

**Comment by jaredbwasserman** [comment] 2022-10-06 08:01
Hi @zuep - Thanks for letting me know. Unfortunately, I am not able to reproduce this issue on my end. Do you have any other addons installed that modify the character sheet?

**Comment by zuep** [comment] 2022-10-06 11:04
hi @jaredbwasserman: yeah i am using a couple of addons.

Most likely it could be ElvUI which is causing the trouble. I'll test it later and comment here again as soon as i am online. :)

**Comment by zuep** [comment] 2022-10-06 15:00
hi @jaredbwasserman: i disabled every othher addon and could move my character sheet again. :)

after enabling the other addons one by one i could identify "RestedXP Guides" as the problematic addon. Hope this helps!

**Comment by jaredbwasserman** [comment] 2022-10-07 05:30
Interesting, thanks for investigating! I will take a look at RestedXP Guides and see what is occurring.

**Comment by jaredbwasserman** [comment] 2022-10-08 07:58
Hi @zuep - I investigated this a bit. Unfortunately, I cannot think of a way to modify Drift code to fix compatibility with RestedXP Guides. The good news, though, is there is a workaround so you can use so it's possible to move the character sheet. If you comment out line `430` of the file `LevelingTracker.lua` (inside the `RXPGuides` folder):
```
OLD:
trackerUi:SetPoint("TOPLEFT", attachment, "TOPRIGHT", offset.x, offset.y)

NEW:
-- trackerUi:SetPoint("TOPLEFT", attachment, "TOPRIGHT", offset.x, offset.y)
```
that should fix the issue. It will make it so the RestedXP Leveling Report frame may not show up in exactly the right place, but this frame can be repositioned.

Let me know if this workaround will work for you.

**Comment by jaredbwasserman** [comment] 2022-10-24 05:27
Closing this out since it's a compatibility issue between Drift and Rested XP Guides. The workaround to comment out a line in RXPGuides is the best I can think of.

**Closed by jaredbwasserman** 2022-10-24 05:27 UTC
Labels: bug
