### ISSUE TITLE
Error opening in AH wrath classic

### ISSUE THREAD

**Issue by codeduph** [jaredbwasserman/drift#47] opened 2023-01-10 05:05 UTC
Got this error when changing the position of the Auction House... using the version [**v2.2.1-wc**]

`1x Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: SideDressUpFrame:SetPoint.
[string "=[C]"]: ?
[string "=[C]"]: in function `SetPoint'
[string "@Interface\FrameXML\DressUpFrames.lua"]:233: in function `SetUpSideDressUpFrame'
[string "@Interface_TBC\AddOns\Blizzard_AuctionUI\Blizzard_AuctionUI.lua"]:208: in function <...TBC\AddOns\Blizzard_AuctionUI\Blizzard_AuctionUI.lua:200>
[string "=[C]"]: in function `Show'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:2214: in function `SetUIPanel'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:2036: in function `ShowUIPanel'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:1927: in function <Interface_Wrath\FrameXML\UIParent.lua:1923>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:2733: in function `ShowUIPanel'
[string "@Interface_TBC\AddOns\Blizzard_AuctionUI\Blizzard_AuctionUI.lua"]:172: in function `AuctionFrame_Show'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:1231: in function <Interface_Wrath\FrameXML\UIParent.lua:756>

Locals:
(*temporary) = SideDressUpFrame {
 0 = <userdata>
 SetScale = <function> defined =[C]:-1
 ResetButton = SideDressUpModelResetButton {
 }
 parentFrame = AuctionFrame {
 }
 DriftModifiable = true
 DriftHookSet = true
 BGBottomLeft = SideDressUpFrameBackgroundBot {
 }
 openWidth = 1020
 closedWidth = 840
 SetPoint = <function> defined =[C]:-1
 BGTopLeft = SideDressUpFrameBackgroundTop {
 }
}
(*temporary) = "TOPLEFT"
(*temporary) = AuctionFrame {
 DriftAboutToSetPoint = false
 SetScale = <function> defined =[C]:-1
 DriftModifiable = true
 DriftHookSet = true
 type = "list"
 0 = <userdata>
 numTabs = 3
 selectedTab = 1
 SetPoint = <function> defined =[C]:-1
}
(*temporary) = "TOPRIGHT"
(*temporary) = -2
(*temporary) = -28
 `

**Comment by jaredbwasserman** [comment] 2023-01-11 08:27
Thanks for letting me know. I will take a look when I have some time.

**Comment by jaredbwasserman** [comment] 2023-01-14 05:49
I am not able to reproduce this issue. Do you have any other addons installed that could be interfering?

**Comment by jaredbwasserman** [comment] 2023-01-17 06:30
My mistake, I am able to reproduce this issue. I'll need to investigate more why this is happening.

**Comment by jaredbwasserman** [comment] 2023-01-22 06:53
Fixed in Drift v2.2.2.

**Closed by jaredbwasserman** 2023-01-22 06:53 UTC
Labels: bug
